demo/config/routes.rb
Demo::Application.routes.draw do
  get "other_methods/math"

  get "other_methods/string"

  get "other_methods/time"

  get "other_methods/directories"

  get "say/hello"

  get "say/goodbye"

end

demo/app/controllers/other_methods_controller.rb
class OtherMethodsController < ApplicationController
  def math
  end

  def string
  end

  def time
  end

  def directories
    @files = Dir.glob('*')
  end
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
  end


end

demo/app/helpers/other_methods_helper.rb
module OtherMethodsHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/other_methods/directories.html.erb
<h1>Directories</h1>
<p>
  <% for file in @files %>
      file name is: <%= file %> ,
  <% end %>
</p>

demo/app/views/other_methods/math.html.erb
<h1>Math</h1>
<p>Addition: <%= 1+2 %></p>

demo/app/views/other_methods/string.html.erb
<h1>String Concatenation</h1>
<p>Concatenation: <%= "cow" + "boy" %></p>

demo/app/views/other_methods/time.html.erb
<h1>Time</h1>
<p>Time in one hour: <%= 1.hour.from_now %></p>

demo/app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
  It was nice having you here.
</p>

<p>
  Say <%= link_to "Hello", say_hello_path %>
</p>

demo/app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>
  It is now <%= @time %>
</p>
<p>
Time to say
<%= link_to "Goodbye", say_goodbye_path %>!
</p>